//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESATouristGuide.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESATouristGuide.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to What to do Favourites.
        /// </summary>
        internal static string AddedToWhatToDoFavourites {
            get {
                return ResourceManager.GetString("AddedToWhatToDoFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you have added some?.
        /// </summary>
        internal static string AddSomeFavourites {
            get {
                return ResourceManager.GetString("AddSomeFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to
        ///favourites.
        /// </summary>
        internal static string AddToFavourites {
            get {
                return ResourceManager.GetString("AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agion Oros.
        /// </summary>
        internal static string AgionOros {
            get {
                return ResourceManager.GetString("AgionOros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is required in order to continue.
        /// </summary>
        internal static string ApplicationCannotStart {
            get {
                return ResourceManager.GetString("ApplicationCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out about nearby destinations using augmented reality technology..
        /// </summary>
        internal static string ARContent {
            get {
                return ResourceManager.GetString("ARContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Reality.
        /// </summary>
        internal static string ARTitle {
            get {
                return ResourceManager.GetString("ARTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art &amp; Life.
        /// </summary>
        internal static string ArtLife {
            get {
                return ResourceManager.GetString("ArtLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols for arrivals in Greece.
        /// </summary>
        internal static string CovidProtocols {
            get {
                return ResourceManager.GetString("CovidProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string Deutsch {
            get {
                return ResourceManager.GetString("Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For full access to the features of the application, activate the location of the device..
        /// </summary>
        internal static string DeviceLocationNA {
            get {
                return ResourceManager.GetString("DeviceLocationNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do something.
        /// </summary>
        internal static string DoSomething {
            get {
                return ResourceManager.GetString("DoSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favourites.
        /// </summary>
        internal static string Favourited {
            get {
                return ResourceManager.GetString("Favourited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FilterOptions {
            get {
                return ResourceManager.GetString("FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastronomy.
        /// </summary>
        internal static string Gastronomy {
            get {
                return ResourceManager.GetString("Gastronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREAT.
        /// </summary>
        internal static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halkidiki.
        /// </summary>
        internal static string Halkidiki {
            get {
                return ResourceManager.GetString("Halkidiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imathia.
        /// </summary>
        internal static string Imathia {
            get {
                return ResourceManager.GetString("Imathia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration.
        /// </summary>
        internal static string Inspiration {
            get {
                return ResourceManager.GetString("Inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experiences.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilkis.
        /// </summary>
        internal static string Kilkis {
            get {
                return ResourceManager.GetString("Kilkis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string KilometersShort {
            get {
                return ResourceManager.GetString("KilometersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language has changed.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected another language..
        /// </summary>
        internal static string LanguageNotChanged {
            get {
                return ResourceManager.GetString("LanguageNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let your friends know about this app.
        /// </summary>
        internal static string LetYourFriendsKnowAboutThisApp {
            get {
                return ResourceManager.GetString("LetYourFriendsKnowAboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lorem {
            get {
                return ResourceManager.GetString("Lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string NaN {
            get {
                return ResourceManager.GetString("NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        internal static string NavigateTo {
            get {
                return ResourceManager.GetString("NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        internal static string Nearby {
            get {
                return ResourceManager.GetString("Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find any favourited item..
        /// </summary>
        internal static string NoFavouritesItem {
            get {
                return ResourceManager.GetString("NoFavouritesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection. No connection found..
        /// </summary>
        internal static string NoInternetConnectionFound {
            get {
                return ResourceManager.GetString("NoInternetConnectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the augmented reality technology, requires access to your camera..
        /// </summary>
        internal static string OnboardingCameraContent {
            get {
                return ResourceManager.GetString("OnboardingCameraContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string OnboardingCameraTitle {
            get {
                return ResourceManager.GetString("OnboardingCameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn everything about your favorite places.
        /// </summary>
        internal static string OnboardingLearnContent {
            get {
                return ResourceManager.GetString("OnboardingLearnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string OnboardingLearnTitle {
            get {
                return ResourceManager.GetString("OnboardingLearnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is used to show you better results in searches and your location on the map. For that reason you have to provide access to your location services..
        /// </summary>
        internal static string OnboardingLocationContent {
            get {
                return ResourceManager.GetString("OnboardingLocationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string OnboardingLocationTitle {
            get {
                return ResourceManager.GetString("OnboardingLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The official application for travelling around Central Macedonia.
        /// </summary>
        internal static string OnboardingWelcomeContent {
            get {
                return ResourceManager.GetString("OnboardingWelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to \n Visit Central Macedonia.
        /// </summary>
        internal static string OnboardWelcomeTitle {
            get {
                return ResourceManager.GetString("OnboardWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the Great destinations.
        /// </summary>
        internal static string OnoardingDiscoverContent {
            get {
                return ResourceManager.GetString("OnoardingDiscoverContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        internal static string Outdoor {
            get {
                return ResourceManager.GetString("Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pella.
        /// </summary>
        internal static string Pella {
            get {
                return ResourceManager.GetString("Pella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieria.
        /// </summary>
        internal static string Pieria {
            get {
                return ResourceManager.GetString("Pieria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to go.
        /// </summary>
        internal static string PlacesToGo {
            get {
                return ResourceManager.GetString("PlacesToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string Politismos {
            get {
                return ResourceManager.GetString("Politismos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favourites.
        /// </summary>
        internal static string RemovedFromFavourites {
            get {
                return ResourceManager.GetString("RemovedFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from
        ///favourites.
        /// </summary>
        internal static string RemoveFromFavourites {
            get {
                return ResourceManager.GetString("RemoveFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea and sun.
        /// </summary>
        internal static string SeaAndSun {
            get {
                return ResourceManager.GetString("SeaAndSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See
        ///details.
        /// </summary>
        internal static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serres.
        /// </summary>
        internal static string Serres {
            get {
                return ResourceManager.GetString("Serres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string SystemDefaultMode {
            get {
                return ResourceManager.GetString("SystemDefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thessaloniki.
        /// </summary>
        internal static string Thessaloniki {
            get {
                return ResourceManager.GetString("Thessaloniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string TimeSpanError {
            get {
                return ResourceManager.GetString("TimeSpanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Guide.
        /// </summary>
        internal static string TouristGuide {
            get {
                return ResourceManager.GetString("TouristGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful.
        /// </summary>
        internal static string Useful {
            get {
                return ResourceManager.GetString("Useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do.
        /// </summary>
        internal static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
    }
}
